[build]
  publish = "build/web"
  command = "if [ ! -d /opt/buildhome/flutter ]; then git clone https://github.com/flutter/flutter.git -b stable --depth 1 /opt/buildhome/flutter; fi && export PATH=\"$PATH:/opt/buildhome/flutter/bin\" && flutter config --enable-web && flutter pub get && flutter build web --release --base-href /"

[build.environment]
  PUB_CACHE = "/opt/buildhome/.pub-cache"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
