name: zhirox_ai_debt_manager
description: Kurdish Sorani RTL Flutter frontend for Zhirox AI Debt.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  shared_preferences: ^2.3.2
  intl: ^0.19.0

flutter:
  uses-material-design: true
